trigger: none

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'Restore dependencies'
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build solution in $(buildConfiguration) configuration'
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/'

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: QodanaScan@2023
  env:
    QODANA_TOKEN: $(QODANA_TOKEN)

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
